server:
  port: 9002

spring:
  application:
    name: baas-frauds
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: baas-frauds-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

baas:
  kafka:
    bootstrap-servers: localhost:9092
    consumer-topic: baas-frauds
    topic: baas-account
