version: '3.8'

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=dynamodb,sns,sqs
      - DEBUG=${DEBUG:-0}
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:- }
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack"
      - "./localstack/init-scripts:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"

  frontend:
    container_name: baas_frontend
    build:
      context: ./baas-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # resolves to host on Linux/WSL2
