server:
  port: 9001

spring:
  application:
    name: baas-onboarding
  jackson:
    property-naming-strategy: SNAKE_CASE

amazon:
  dynamodb:
    endpoint: http://localhost:4566
  aws:
    region: us-east-1

baas:
  kafka:
    bootstrap-servers: localhost:9092
    topic: baas-onboarding
