server:
  port: 9003

spring:
  application:
    name: baas-account
  jackson:
    property-naming-strategy: SNAKE_CASE

amazon:
  dynamodb:
    endpoint: http://localhost:4566
  aws:
    region: us-east-1
