server:
  port: 9003

spring:
  application:
    name: baas-account
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      observation-enabled: true
    template:
      observation-enabled: true
    consumer:
      group-id: baas-account-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

amazon:
  dynamodb:
    endpoint: http://localhost:4566
  aws:
    region: us-east-1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}

baas:
  kafka:
    bootstrap-servers: localhost:9092
    consumer-topic: baas-account
    topic: baas-webhook
